age_me = (12)
age_mother = (37)
age_father = (60)
age_sister = (7)
age_brother = (11)
print(int(age_mother)+25)
print(int(age_father)+25)
print(int(age_brother)+25)
print(int(age_me)+25)
print(int(age_sister)+25)